### ISSUE TITLE
author information missing

### ISSUE THREAD

**Issue by harshzalavadiya** [strandls/biodiv-observation#2]
While using `observation/show` endpoint only `authorId` is coming `authorName` and `authorImage` keys are missing

**Comment by rsprabha** [comment]
Has this not been tested with swagger pojo classes?

Prabkakar

**Comment by harshzalavadiya** [comment]
Fixed on https://github.com/strandls/biodiv-observation/commit/ce08a438a03f7b105d26ac51bf1e2b4f82b497b0
